# Generated by Django 3.2.9 on 2021-12-12 20:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inference_time', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='captures/')),
                ('pred_1', models.CharField(blank=True, max_length=50, null=True)),
                ('conf_1', models.FloatField(blank=True, null=True)),
                ('pred_2', models.CharField(blank=True, max_length=50, null=True)),
                ('conf_2', models.FloatField(blank=True, null=True)),
                ('pred_3', models.CharField(blank=True, max_length=50, null=True)),
                ('conf_3', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('bio', models.TextField(null=True)),
                ('content_type', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
