# Generated by Django 3.2.9 on 2021-11-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vastapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('inference_time', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
