# Generated by Django 3.2.9 on 2021-11-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vastapp', '0002_capture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
